### ISSUE TITLE
Swagger UI fails to invoke API endpoints

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#95] opened 2019-04-03 19:24 UTC
The error is `TypeError: Not allowed to request resource`. This is in all likelihood because the KB server is now on HTTPS, and the requests seem to be assuming HTTP?

**Comment by balhoff** [comment] 2019-04-03 19:39
I just added the `https` scheme to the swagger definition. So if you select this from the menu at the top it will work.

But should I remove the `http` scheme? I guess the issue is that when you load the swagger UI it automatically switches you to https.

**Comment by hlapp** [comment] 2019-04-03 19:46
The issue is that the `http` endpoints don't respond with a result but with a `301` redirect.

The curl command displayed won't work with that either, one then has to add '-L', and for POST requests also `--post301` or curl converts the POST into GET when trying the redirected-to URL.

So having an option there when really there isn't due to how the server is configured doesn't make sense.

**Comment by balhoff** [comment] 2019-04-03 20:07
Fixed now.

**Closed by balhoff** 2019-04-03 20:07 UTC
Labels: bug, holdup for client
